//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGCAService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://www.serviceobjects.com")]
    public partial class Location : object
    {
        
        private AGCAService.Error ErrorField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string PostalCodeField;
        
        private string MatchCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGCAService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MatchCode
        {
            get
            {
                return this.MatchCodeField;
            }
            set
            {
                this.MatchCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.serviceobjects.com")]
    public partial class Error : object
    {
        
        private string DescField;
        
        private string NumberField;
        
        private string LocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostalCodeInfo", Namespace="http://www.serviceobjects.com")]
    public partial class PostalCodeInfo : object
    {
        
        private AGCAService.Error ErrorField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string PostalCodeField;
        
        private string TimeZoneField;
        
        private string DSTField;
        
        private string AreaCodeField;
        
        private string CityField;
        
        private string CityPopulationField;
        
        private string ProvinceField;
        
        private string ProvinceAbbreviationField;
        
        private string DMAField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGCAService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TimeZone
        {
            get
            {
                return this.TimeZoneField;
            }
            set
            {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DST
        {
            get
            {
                return this.DSTField;
            }
            set
            {
                this.DSTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CityPopulation
        {
            get
            {
                return this.CityPopulationField;
            }
            set
            {
                this.CityPopulationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ProvinceAbbreviation
        {
            get
            {
                return this.ProvinceAbbreviationField;
            }
            set
            {
                this.ProvinceAbbreviationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DMA
        {
            get
            {
                return this.DMAField;
            }
            set
            {
                this.DMAField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="AGCAService.IGCCSoapService")]
    public interface IGCCSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCCSoapService/GetGeoLocation", ReplyAction="http://www.serviceobjects.com/IGCCSoapService/GetGeoLocationResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Location")]
        System.Threading.Tasks.Task<AGCAService.Location> GetGeoLocationAsync(string Address, string Municipality, string Province, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCCSoapService/GetGeoLocationByMunicipalityProvinc" +
            "e", ReplyAction="http://www.serviceobjects.com/IGCCSoapService/GetGeoLocationByMunicipalityProvinc" +
            "eResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Location")]
        System.Threading.Tasks.Task<AGCAService.Location> GetGeoLocationByMunicipalityProvinceAsync(string Municipality, string Province, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCCSoapService/GetPostalCodeInfo", ReplyAction="http://www.serviceobjects.com/IGCCSoapService/GetPostalCodeInfoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="PostalCodeInfo")]
        System.Threading.Tasks.Task<AGCAService.PostalCodeInfo> GetPostalCodeInfoAsync(string PostalCode, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGCCSoapServiceChannel : AGCAService.IGCCSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class GCCSoapServiceClient : System.ServiceModel.ClientBase<AGCAService.IGCCSoapService>, AGCAService.IGCCSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GCCSoapServiceClient() : 
                base(GCCSoapServiceClient.GetDefaultBinding(), GCCSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DOTSGeoCoderCanada.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCCSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GCCSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), GCCSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCCSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GCCSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCCSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GCCSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCCSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AGCAService.Location> GetGeoLocationAsync(string Address, string Municipality, string Province, string PostalCode, string LicenseKey)
        {
            return base.Channel.GetGeoLocationAsync(Address, Municipality, Province, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGCAService.Location> GetGeoLocationByMunicipalityProvinceAsync(string Municipality, string Province, string LicenseKey)
        {
            return base.Channel.GetGeoLocationByMunicipalityProvinceAsync(Municipality, Province, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGCAService.PostalCodeInfo> GetPostalCodeInfoAsync(string PostalCode, string LicenseKey)
        {
            return base.Channel.GetPostalCodeInfoAsync(PostalCode, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSGeoCoderCanada))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSGeoCoderCanada))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/GCC/soap.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GCCSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.DOTSGeoCoderCanada);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GCCSoapServiceClient.GetEndpointAddress(EndpointConfiguration.DOTSGeoCoderCanada);
        }
        
        public enum EndpointConfiguration
        {
            
            DOTSGeoCoderCanada,
        }
    }
}
